language: go
go:
    - '1.10'
    - dev
sudo: required
# install先安装依赖
install:
    - go get -u github.com/gorilla/mux
    - go get -u github.com/gorilla/sessions
    - go get -u github.com/op/go-logging
    - mkdir -p $GOPATH/src/gopkg.in/mgo.v2 && git clone -b v2 https://github.com/go-mgo/mgo.git $GOPATH/src/gopkg.in/mgo.v2
    - mkdir -p $GOPATH/src/golang.org/x/crypto && git clone https://github.com/golang/crypto $GOPATH/src/golang.org/x/crypto
# script运行命令
script:
    - pwd
    - cd src/ && go build main.go
# services包含所需的服务
services:
    - mongodb
before_install:
    - openssl aes-256-cbc -K $encrypted_7669d81b39c5_key -iv $encrypted_7669d81b39c5_iv
      -in id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
after_success:
    - ssh ubuntu@118.89.35.145 "cd ~/ABT-server && sh ./build.sh"
addons:
    ssh_known_hosts: 118.89.35.145 # 自己的服务器ip地址
